name: resilientclassroom
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  modal_progress_hud: ^0.1.3
  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.0
  mantras: ^0.0.3
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  fonts:
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Bold.ttf


  uses-material-design: true

  assets:
    - images/
